version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx truffle test

  # This job uses the SuperHDWalletProvider to sign the transactions directly in the runner using a mnemonic 12 and still
  # allow you to keep track of all the details of the deployment inside the platform. 
  deploy_to_rinkeby_automatic:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx truffle migrate --network rinkeby --reset
            - run: npx superblocks-cli collect-artifacts

  # This job uses the ManualSignProvider to be able to securely and manually sign each transactions a given deployment is creating without ever
  # needing to share your private key with us.
  deploy_to_rinkeby_manually:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npx truffle migrate --network rinkeby_metamask --reset
            - run: npx superblocks-cli collect-artifacts


workflows:
    build-and-test:
      jobs:
        - build-and-test
    deploy_to_testnets:
      jobs:
        - deploy_to_rinkeby_automatic:
            filters:
              only: 
                - master
        - deploy_to_rinkeby_manually:
            type: approval
            filters:
              only: 
                - master